package dao.queries;

public enum queriesPersona {

	 INSERT_PERSONA("INSERT INTO PERSONAS(DNI, NOMBRE, APELLIDO, MAIL, TELEFONO, ID_TIPO, DIRECCION, ID_LOCALIDAD, FECHA_NACIMIENTO, ID_ESTADO) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"),

	 ACTUALIZAR_PERSONA("UPDATE PERSONAS SET NOMBRE = ?, APELLIDO = ?, MAIL = ?, TELEFONO = ?, ID_TIPO = ?, DIRECCION = ?, ID_LOCALIDAD = ?, FECHA_NACIMIENTO = ? WHERE DNI = ? "),

	 ELIMINAR_PERSONA("UPDATE PERSONAS SET ID_ESTADO = 0 WHERE LEGAJO = ?"),

	 GET_LISTA_PERSONAS("SELECT LEGAJO, DNI, NOMBRE, APELLIDO, MAIL, TELEFONO FROM PERSONAS WHERE ID_ESTADO = 1"),

	 GET_PERSONA("SELECT DNI, NOMBRE, APELLIDO, MAIL, TELEFONO, ID_TIPO, DIRECCION, ID_LOCALIDAD, FECHA_NACIMIENTO FROM PERSONAS WHERE LEGAJO = ?"),

	 GET_REGISTRO_DNI_EXISTENTE("SELECT 1 FROM PERSONAS WHERE DNI = ?"),

	 GET_REGISTRO_EMAIL_EXISTENTE("SELECT 1 FROM PERSONAS WHERE MAIL = ?"),
	 
	 VM_DATOS_PROFESORES("SELECT DISTINCT LEGAJO,DNI,NOMBRE,APELLIDO,MAIL,TELEFONO,DIRECCION,EDAD,CURSOS,USUARIO,CONTRASEÑA,LOCALIDAD,PROVINCIA FROM VW_PROFESORES"),

	 PR_INSERT_PERSONA("CALL PR_INSERT_USER_PROFESOR(?, ?, ?, ?, ?, ?, ?, ?, ?)"),

	 ;
	
	private String query;

	private queriesPersona(String valor) {
		this.setQuery(valor);
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

}
